version: '3.8'

services:
  streamlit:
    build:
      context: ..
      dockerfile: streamlit/Dockerfile
    image: running-with-prefect-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./.secrets.toml:/app/.streamlit/secrets.toml:ro
      - ./app.py:/app/app.py
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

